name: scan-service
on: [push]
permissions:
  contents: read
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: build
        env:
          CI_COMMIT_SHA: ${{ github.sha }}
          CI_COMMIT_TAG: ${{ github.ref }}
          EXEC_NAME: scan-service
        run: make build
      - name: Step 3 - Use the Upload ArtifactGitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: bin
  docker:
    needs: [go-build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: executable
      - name: move executable to bin folder
        run: |
          mkdir bin && mv scan-service ./bin/scan-service

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: infrastructure/Dockerfile
          push: true
          tags: sudhagarkv/scan-service:latest

  docker-migrate:
    needs: [go-build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: infrastructure/Migrate.Dockerfile
          push: true
          tags: sudhagarkv/scan-migrate:latest
